# Generated by Django 2.2.5 on 2019-09-07 07:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='请输入标题不超过30个字', max_length=30, unique=True, verbose_name='推文标题')),
                ('summary', models.CharField(blank=True, help_text='请输入简要概括，不超过200个字', max_length=200, null=True, verbose_name='推文简要概括')),
                ('created_time', models.DateField(auto_now=True)),
                ('body', ckeditor.fields.RichTextField(help_text='上传的图片宽不要超过777px', verbose_name='推文')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(help_text='请输入评论,不超过300字', max_length=300, verbose_name='评论')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_profile', models.CharField(help_text='请添加成员简介', max_length=200, verbose_name='成员简介')),
                ('member_picurl', models.URLField(help_text='请添加成员头像链接', verbose_name='成员头像')),
            ],
        ),
        migrations.CreateModel(
            name='Mv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mv_title', models.CharField(help_text='请输入标题,不超过300字', max_length=300, verbose_name='mv标题')),
                ('mv_pic_url', models.URLField(help_text='请添加视频封面链接', verbose_name='封面链接')),
                ('mv_url', models.URLField(help_text='请添加视频链接', verbose_name='视频链接')),
                ('mv_uptime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='请选择预计日期', verbose_name='预计日期')),
                ('agenda', models.CharField(help_text='请输入预计事项,不超过100字', max_length=100, verbose_name='预计事项')),
            ],
        ),
    ]
